# Generated by Django 4.0.2 on 2022-04-06 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_date_published_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 10, 40, 18, 787442, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
